version: '3.8'
services: 
  frontend:
    image: youssef11gaber10/react-service:latest
    container_name: nginx-container
    ports:
      - 3000:80
    networks:
      - front_backend
    depends_on:
      - backend
      - backend2
      - backend3

  backend:
    image: youssef11gaber10/flask-service:latest
    container_name: backend-server1
    hostname: backend1-server
    expose:
      - 5000
    env_file:
        - .env

    networks:
      - front_backend
      - backend_postgres
    depends_on:
      - postgres
      
  backend2: # this is for test load balancer of nginx
    image: youssef11gaber10/flask-service:latest
    container_name: backend-server2
    hostname: backend2-server
    expose:
      - 5000
    env_file:
        - .env
    networks:
      - front_backend
      - backend_postgres
    depends_on:
      - postgres
      - backend
  
  backend3: # this is for test load balancer of nginx
    image: youssef11gaber10/flask-service:latest
    container_name: backend-server3
    hostname: backend3-server
    expose:
      - 5000
    env_file:
        - .env
    networks:
      - front_backend
      - backend_postgres
    depends_on:
      - postgres
      - backend
      - backend2
  



  postgres:
    image: postgres:16
    container_name:  postgres-container
    expose:
      - 5432
    env_file:
      - .env
    networks:
      - backend_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  

networks:
  front_backend:
  backend_postgres:

volumes:
  postgres_data:
    