version: '3.8'
services: 
  frontend:
    image: youssef11gaber10/react-service:latest
    container_name: nginx-container
    ports:
      - 3000:80
    networks:
      - front_backend
    # depends_on:
    #   - backend
    #   - backend2
    #   - backend3
    depends_on:
      backend:
        condition: service_healthy
      backend2:
        condition: service_healthy
      # backend3:
      #   condition: service_healthy

  backend:
    image: youssef11gaber10/flask-service:latest
    container_name: backend-server1
    hostname: backend1-server
    expose:
      - 5000
    env_file:
        - .env

    networks:
      - front_backend
      - backend_postgres
    # restart: always # if he fails cause any thing like db not yet ready and he fails for that he will be restart
    # depends_on:
    #   - postgres
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request,sys; sys.exit(0) if urllib.request.urlopen('http://localhost:5000/api/tasks').getcode()==200 else sys.exit(1)"]
      interval: 5s # check every 5 seconds
      timeout: 3s # wait for 3 seconds 
      retries: 5 # try 5 times after them with no response he will consider the status unhealthy

      
  backend2: # this is for test load balancer of nginx
    image: youssef11gaber10/flask-service:latest
    container_name: backend-server2
    hostname: backend2-server
    expose:
      - 5000
    env_file:
        - .env
    networks:
      - front_backend
      - backend_postgres
    # restart: always # if he fails cause any thing like db not yet ready and he fails for that he will be restart
    depends_on:
      backend:
        condition: service_healthy
    # depends_on:
    #   - postgres
    #   - backend
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request,sys; sys.exit(0) if urllib.request.urlopen('http://localhost:5000/api/tasks').getcode()==200 else sys.exit(1)"]
      interval: 5s # check every 5 seconds
      timeout: 3s # wait for 3 seconds 
      retries: 5 # try 5 times after them with no response he will consider the status unhealthy

  
  # backend3: # this is for test load balancer of nginx
  #   image: youssef11gaber10/flask-service:latest
  #   container_name: backend-server3
  #   hostname: backend3-server
  #   expose:
  #     - 5000
  #   env_file:
  #       - .env
  #   networks:
  #     - front_backend
  #     - backend_postgres
  #   # restart: always # if he fails cause any thing like db not yet ready and he fails for that he will be restart
  #   # depends_on:
  #   #   - postgres
  #   #   - backend
  #   #   - backend2
  #   depends_on:
  #     backend:
  #       condition: service_healthy
  #     backend2:
  #       condition: service_healthy
  #   healthcheck:
  #     test: ["CMD", "python", "-c", "import urllib.request,sys; sys.exit(0) if urllib.request.urlopen('http://localhost:5000/api/tasks').getcode()==200 else sys.exit(1)"]
  #     interval: 5s # check every 5 seconds
  #     timeout: 3s # wait for 3 seconds 
  #     retries: 5 # try 5 times after them with no response he will consider the status unhealthy

  



  postgres:
    image: postgres:16
    container_name:  postgres-container
    expose:
      - 5432
    env_file:
      - .env
    networks:
      - backend_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5

    

networks:
  front_backend:
  backend_postgres:

volumes:
  postgres_data:
    